version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
    volumes:
      - ./data:/var/lib/mysql

  web:
    build:
      args:
        user: henry
        uid: 1000
      context: ./
    ports:
      - 8000:80
    volumes:
      - ./todo-app:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: todo_app
      DB_USERNAME: root
      DB_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
        - 8001:80
    environment:
        - PMA_ARBITRARY=1
    depends_on:
        - db
